{
  "name": "@react-deephoc/errorfallback",
  "version": "1.0.0-beta.53",
  "description": "React Deephoc @react-deephoc/errorfallback",
  "type": "module",
  "main": "deepErrorFallback.js",
  "exports": {
    ".": "./deepErrorFallback.js"
  },
  "files": [
    "**/*.js",
    "**/*.d.ts"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/react-deephoc/react-deephoc.git"
  },
  "keywords": [
    "react",
    "deep",
    "hoc"
  ],
  "author": "sarimarton@gmail.com",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/react-deephoc/react-deephoc/issues"
  },
  "homepage": "https://github.com/react-deephoc/react-deephoc#readme",
  "dependencies": {
    "react-error-boundary": "^4.0.10"
  },
  "peerDependencies": {
    "react": "^16.0.0 || ^17.0.0 || ^18.0.0",
    "react-deephoc": "^1.0.0-beta",
    "react-dom": "^16.0.0 || ^17.0.0 || ^18.0.0"
  },
  "publishConfig": {
    "access": "public"
  }
}
